/*
 * generated by Xtext 2.11.0
 */
package fr.cea.modane.ide

import com.google.inject.Guice
import fr.cea.modane.ModaneRuntimeModule
import fr.cea.modane.ModaneStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class ModaneIdeSetup extends ModaneStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new ModaneRuntimeModule, new ModaneIdeModule))
	}
	
}
