MODULE_NAME=Hydro
EXAMPLE_ADDITIONAL_LIBS=-Wl,-rpath,. -L. 
EXAMPLE_ADDITIONAL_TARGETS=

include ../../Makefile.inc
include ../../Makefile.module

fullclean::
	make clean
	\rm -f __*.h *.axl *_axl.h ${MODULE_NAME}Module.* *.modane
