/*
 * generated by Xtext 2.11.0
 */
package fr.cea.modane.scoping

import org.eclipse.xtext.scoping.impl.AbstractDeclarativeScopeProvider

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
class ModaneScopeProvider extends AbstractDeclarativeScopeProvider 
{
//	def scope_Reference_target(Reference ctx, EReference ref) 
//	{ 
//		createSimpleScope(ctx.target.name, null)
//	}
//		
//	def scope_VarReference_variable(VarReference ctx, EReference ref) 
//	{ 
//		createSimpleScope(ctx.variable.name, ctx.variable)
//	}
//	
//	def scope_EntryPoint_calls(EntryPoint ctx, EReference ref)
//	{
//		val descriptions = ctx.calls.map[x | EObjectDescription.create(x.name, x)]
//		return new SimpleScope(descriptions)		
//	}
//	
//	def scope_Function_calls(Function ctx, EReference ref)
//	{
//		val descriptions = ctx.calls.map[x | EObjectDescription.create(x.name, x)]
//		return new SimpleScope(descriptions)		
//	}
//
//	private def createSimpleScope(String name, EObject object)
//	{
//		val descriptions = #[EObjectDescription.create(name, object)]
//		return new SimpleScope(descriptions)		
//	}
}
